#!/usr/bin/env python

import sys

# Given a histogram file generated by BEDTools GenomeCoverageBed, prints the following values:
# - chromosome
# - number of bases
# - total read-bases
# - average coverage (read_bases / bases)
# - median coverage (estimate) 
# - percentage of bases with zero coverage

total_depth = 0
chr_len = 0.0
num_seen = 0

middle = 0
median = 0

first = True
passed_middle = False

read_any_lines = False
chrom = "NA"

pct_zero = 0.0

for line in sys.stdin:
	fields = line.split()
	if read_any_lines and fields[0] != chrom:
		print "{0}\t{1}\t{2}\t{3}\t{4}\t{5}".format(chrom, num_seen, total_depth, total_depth/chr_len, median, pct_zero)

		total_depth = 0
		chr_len = 0.0
		num_seen = 0		
		middle = 0
		median = 0		
		first = True
		passed_middle = False

	read_any_lines = True
	chrom = fields[0]
	depth = long(fields[1])
	num = long(fields[2])
	if (depth == 0):
		pct_zero = float(fields[4])
	total_depth += depth * num
	if first:
		chr_len = float(fields[3])
		middle = chr_len / 2
		first = False
	if (not passed_middle) and (num + num_seen > middle):
		passed_middle = True
		median = depth
	num_seen += num

print "{0}\t{1}\t{2}\t{3}\t{4}\t{5}".format(chrom, num_seen, total_depth, total_depth/chr_len, median, pct_zero)

